name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**/*.tf'
      - '.github/workflows/release.yml'

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: write
  packages: write
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.repository_owner == 'terraform-xops-modules'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
